# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ElricHuang's Blog
email: elrichuang@qq.com
description: > # this means to ignore newlines until "baseurl:"
  黄伟明（ElricHuang）的博客，分享微信，PHP（Codeigniter，Symfony），HTML5，Git，MySQL，Linux，iOS，Android，Javascript，C/C++等经验。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://elrichuang.github.io" # the base hostname & protocol for your site
twitter_username: elrichuang
github_username:  elrichuang

# Build settings
markdown: kramdown
